### ISSUE TITLE
FC1: 透视浏览器隐藏的密码

### ISSUE THREAD

**Issue by sunwu51** [sunwu51/notebook#3]
如果浏览器中存储的密码忘记了，怎么办，只能看到***？
或者想偷看别人浏览器存储的密码？   

直接在浏览器控制台输出document.querySelector('input[type=password]').value就可以啦 。

租房子光猫密码是默认记住在浏览器中的，我就是这样获取出来的，然后改成了桥接拨号:)
![pwd](https://user-images.githubusercontent.com/15844103/87251102-d1f9b780-c49b-11ea-8723-b91c249acbdf.gif)

**Comment by Lengff** [comment]
[img](http://lengff.com/lengff/img/getpassword.gif)

**Comment by Lengff** [comment]
这样会不会更好呢？[点我查看图片](http://lengff.com/lengff/img/getpassword.gif)

**Comment by wunairen** [comment]
感谢dalao分享

**Comment by CodeDiggerSuzl** [comment]
点赞

**Comment by RickMeng** [comment]
秀

**Comment by orangejx** [comment]
> 这样会不会更好呢？![点我查看图片](https://camo.githubusercontent.com/c90b984cc8608cb7741e0a950c126b1ce24a9be6/687474703a2f2f6c656e6766662e636f6d2f6c656e6766662f696d672f67657470617373776f72642e676966)

其实直接将type="password"中的password删掉就可以了，不用再次输入text的

**Comment by liaoshuguang** [comment]
太秀了
