### ISSUE TITLE
FC4: 如何快速启动一个http服务

### ISSUE THREAD

**Issue by sunwu51** [sunwu51/notebook#6]
有时候我们需要快速的启动一个http的服务器，将当前目录的文件放映射出去。

像nginx或者apache httpd等服务器，安装和配置都是很麻烦的，使用下面的几种方式则可以更快的启动服务。

# 1 借助编程语言
如果机器上刚好安装了python、php、ruby等，那么就可以一行指令搞定当前目录啦。
```bash
#  python 3.x(2.x的就不说了)
python3 -m http.server

# php
php -S localhost:8080

# ruby
ruby -run -e httpd . -p 8080
```
或者稍微麻烦一点，一些编程语言的库也能做到，例如nodejs
```bash
# 安装http-server
npm i -g http-server
# 运行
http-server -p 8080
```
#  2 使用二进制包
可以自己写一个提供http服务的程序，然后将程序打包为二进制文件，放到互联网上，这样要用到的时候，就去下载下来，直接运行二进制文件就可以啦，不需要安装任何语言环境了。我好久之前基于gin写了一个这样的小工具，如果是linux下就可以这样使用。
```bash
# 下载二进制文件(mac则将linux改成mac，win则改为win并加.exe后缀)
wget -O server  https://github.com/sunwu51/Tool/releases/download/2/server_linux_amd64

# 增加可执行权限
chmod +x server

# 运行
./server -port 8080 -assets .
```

**Comment by codehzy** [comment]
可以借助anywhere这个库，更快捷
